apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.configmap.postgres.user }}
  POSTGRES_DB: {{ .Values.configmap.postgres.db }}
  POSTGRES_HOSTNAME: {{ .Values.configmap.postgres.hostname }}
