apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  GITHUB_CLIENT_ID: {{ .Values.secret.github.client_id }}
  GITHUB_CLIENT_SECRET: {{ .Values.secret.github.client_secret }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres.password }}
